import type { AssetClass } from "./types";

type CatalogInstrument = {
  id: string;
  displaySymbol: string;
  name: string;
  category: "currencies" | "stocks" | "indexes" | "commodities" | "crypto_usdt" | "crypto_eurt";
  tvSymbol: string;
  assetClass: AssetClass;
  tradable: boolean;
  yahooTicker?: string;
  binancePair?: string;
};

function fxYahoo(displaySymbol: string): string {
  const [base, quote] = displaySymbol.split("/");
  if (base === "USD" && quote === "JPY") return "JPY=X";
  if (base === "USD" && quote === "CAD") return "CAD=X";
  if (base === "USD" && quote === "CHF") return "CHF=X";
  if (quote === "USD") return `${base}USD=X`;
  return `${base}${quote}=X`;
}

function fx(id: string, displaySymbol: string, name: string): CatalogInstrument {
  const tv = `FX:${displaySymbol.replace("/", "")}`;
  return {
    id,
    displaySymbol,
    name,
    category: "currencies",
    tvSymbol: tv,
    assetClass: "us_equity",
    tradable: true,
    yahooTicker: fxYahoo(displaySymbol),
  };
}

function stk(id: string, ticker: string, name: string, exchange: "NASDAQ" | "NYSE" = "NASDAQ"): CatalogInstrument {
  return {
    id,
    displaySymbol: ticker,
    name,
    category: "stocks",
    tvSymbol: `${exchange}:${ticker}`,
    assetClass: "us_equity",
    tradable: true,
    yahooTicker: ticker,
  };
}

function cmd(id: string, displaySymbol: string, name: string, tvSymbol: string, yahooTicker: string): CatalogInstrument {
  return {
    id,
    displaySymbol,
    name,
    category: "commodities",
    tvSymbol,
    assetClass: "us_equity",
    tradable: true,
    yahooTicker,
  };
}

function idx(id: string, displaySymbol: string, name: string, tvSymbol: string, yahooTicker: string): CatalogInstrument {
  return {
    id,
    displaySymbol,
    name,
    category: "indexes",
    tvSymbol,
    assetClass: "us_equity",
    tradable: true,
    yahooTicker,
  };
}

function cr(id: string, base: string, name: string): CatalogInstrument {
  const pair = `${base}/USDT`;
  const sym = `${base}USDT`;
  return {
    id,
    displaySymbol: pair,
    name,
    category: "crypto_usdt",
    tvSymbol: `BINANCE:${sym}`,
    assetClass: "crypto",
    tradable: true,
    binancePair: sym,
  };
}

function cre(id: string, base: string, name: string): CatalogInstrument {
  const pair = `${base}/EUR`;
  const sym = `${base}EUR`;
  return {
    id,
    displaySymbol: pair,
    name,
    category: "crypto_eurt",
    tvSymbol: `BINANCE:${sym}`,
    assetClass: "crypto",
    tradable: true,
    binancePair: sym,
  };
}

const G10 = ["EUR", "GBP", "AUD", "NZD", "USD", "CAD", "CHF", "JPY"] as const;
const G10_NAMES: Record<string, string> = {
  EUR: "Euro",
  GBP: "British Pound",
  AUD: "Australian Dollar",
  NZD: "New Zealand Dollar",
  USD: "US Dollar",
  CAD: "Canadian Dollar",
  CHF: "Swiss Franc",
  JPY: "Japanese Yen",
};

function buildG10Fx(): CatalogInstrument[] {
  const out: CatalogInstrument[] = [];
  for (const base of G10) {
    for (const quote of G10) {
      if (base === quote) continue;
      const displaySymbol = `${base}/${quote}`;
      const id = displaySymbol.toLowerCase().replace("/", "");
      const name = `${G10_NAMES[base]} / ${G10_NAMES[quote]}`;
      out.push(fx(id, displaySymbol, name));
    }
  }
  return out;
}

const FX_EXOTICS: Array<[string, string, string]> = [
  ["usdmxn", "USD/MXN", "US Dollar / Mexican Peso"],
  ["usdzar", "USD/ZAR", "US Dollar / South African Rand"],
  ["usdtry", "USD/TRY", "US Dollar / Turkish Lira"],
  ["usdsek", "USD/SEK", "US Dollar / Swedish Krona"],
  ["usdnok", "USD/NOK", "US Dollar / Norwegian Krone"],
  ["usddkk", "USD/DKK", "US Dollar / Danish Krone"],
  ["usdsgd", "USD/SGD", "US Dollar / Singapore Dollar"],
  ["usdhkd", "USD/HKD", "US Dollar / Hong Kong Dollar"],
  ["usdpln", "USD/PLN", "US Dollar / Polish Zloty"],
  ["usdczk", "USD/CZK", "US Dollar / Czech Koruna"],
  ["usdhuf", "USD/HUF", "US Dollar / Hungarian Forint"],
  ["usdils", "USD/ILS", "US Dollar / Israeli Shekel"],
  ["usdcnh", "USD/CNH", "US Dollar / Offshore Yuan"],
  ["eurpln", "EUR/PLN", "Euro / Polish Zloty"],
  ["eurtry", "EUR/TRY", "Euro / Turkish Lira"],
  ["eursek", "EUR/SEK", "Euro / Swedish Krona"],
  ["eurnok", "EUR/NOK", "Euro / Norwegian Krone"],
  ["gbpzar", "GBP/ZAR", "British Pound / South African Rand"],
  ["audsgd", "AUD/SGD", "Australian Dollar / Singapore Dollar"],
];

export const FX_INSTRUMENTS: CatalogInstrument[] = [
  ...buildG10Fx(),
  ...FX_EXOTICS.map(([id, sym, name]) => fx(id, sym, name)),
];

/** US & global large/mid cap — metadata only; live quote on demand for selected symbol. */
const STOCK_ROWS: Array<[string, string, "NASDAQ" | "NYSE"]> = [
  ["AAPL", "Apple Inc.", "NASDAQ"],
  ["MSFT", "Microsoft Corporation", "NASDAQ"],
  ["NVDA", "NVIDIA Corporation", "NASDAQ"],
  ["AMZN", "Amazon.com Inc.", "NASDAQ"],
  ["GOOGL", "Alphabet Inc. Class A", "NASDAQ"],
  ["GOOG", "Alphabet Inc. Class C", "NASDAQ"],
  ["META", "Meta Platforms Inc.", "NASDAQ"],
  ["TSLA", "Tesla Inc.", "NASDAQ"],
  ["BRK-B", "Berkshire Hathaway Class B", "NYSE"],
  ["AVGO", "Broadcom Inc.", "NASDAQ"],
  ["JPM", "JPMorgan Chase & Co.", "NYSE"],
  ["LLY", "Eli Lilly and Company", "NYSE"],
  ["V", "Visa Inc.", "NYSE"],
  ["UNH", "UnitedHealth Group", "NYSE"],
  ["XOM", "Exxon Mobil Corporation", "NYSE"],
  ["MA", "Mastercard Incorporated", "NYSE"],
  ["COST", "Costco Wholesale", "NASDAQ"],
  ["PG", "Procter & Gamble", "NYSE"],
  ["HD", "Home Depot", "NYSE"],
  ["JNJ", "Johnson & Johnson", "NYSE"],
  ["ABBV", "AbbVie Inc.", "NYSE"],
  ["NFLX", "Netflix Inc.", "NASDAQ"],
  ["CRM", "Salesforce Inc.", "NYSE"],
  ["BAC", "Bank of America", "NYSE"],
  ["ORCL", "Oracle Corporation", "NYSE"],
  ["MRK", "Merck & Co.", "NYSE"],
  ["AMD", "Advanced Micro Devices", "NASDAQ"],
  ["CVX", "Chevron Corporation", "NYSE"],
  ["KO", "Coca-Cola Company", "NYSE"],
  ["PEP", "PepsiCo Inc.", "NYSE"],
  ["WMT", "Walmart Inc.", "NYSE"],
  ["TMO", "Thermo Fisher Scientific", "NYSE"],
  ["ADBE", "Adobe Inc.", "NASDAQ"],
  ["CSCO", "Cisco Systems", "NASDAQ"],
  ["ACN", "Accenture plc", "NYSE"],
  ["MCD", "McDonald's Corporation", "NYSE"],
  ["LIN", "Linde plc", "NASDAQ"],
  ["ABT", "Abbott Laboratories", "NYSE"],
  ["DHR", "Danaher Corporation", "NYSE"],
  ["INTC", "Intel Corporation", "NASDAQ"],
  ["INTU", "Intuit Inc.", "NASDAQ"],
  ["TXN", "Texas Instruments", "NASDAQ"],
  ["QCOM", "Qualcomm Incorporated", "NASDAQ"],
  ["CMCSA", "Comcast Corporation", "NASDAQ"],
  ["DIS", "Walt Disney Company", "NYSE"],
  ["VZ", "Verizon Communications", "NYSE"],
  ["PM", "Philip Morris International", "NYSE"],
  ["IBM", "International Business Machines", "NYSE"],
  ["AMAT", "Applied Materials", "NASDAQ"],
  ["GE", "GE Aerospace", "NYSE"],
  ["CAT", "Caterpillar Inc.", "NYSE"],
  ["NOW", "ServiceNow Inc.", "NYSE"],
  ["ISRG", "Intuitive Surgical", "NASDAQ"],
  ["GS", "Goldman Sachs Group", "NYSE"],
  ["BKNG", "Booking Holdings", "NASDAQ"],
  ["AXP", "American Express", "NYSE"],
  ["MS", "Morgan Stanley", "NYSE"],
  ["RTX", "RTX Corporation", "NYSE"],
  ["UBER", "Uber Technologies", "NYSE"],
  ["SPGI", "S&P Global Inc.", "NYSE"],
  ["PFE", "Pfizer Inc.", "NYSE"],
  ["T", "AT&T Inc.", "NYSE"],
  ["HON", "Honeywell International", "NASDAQ"],
  ["BLK", "BlackRock Inc.", "NYSE"],
  ["SYK", "Stryker Corporation", "NYSE"],
  ["TJX", "TJX Companies", "NYSE"],
  ["C", "Citigroup Inc.", "NYSE"],
  ["BA", "Boeing Company", "NYSE"],
  ["AMGN", "Amgen Inc.", "NASDAQ"],
  ["DE", "Deere & Company", "NYSE"],
  ["LOW", "Lowe's Companies", "NYSE"],
  ["SBUX", "Starbucks Corporation", "NASDAQ"],
  ["GILD", "Gilead Sciences", "NASDAQ"],
  ["MDLZ", "Mondelez International", "NASDAQ"],
  ["ADI", "Analog Devices", "NASDAQ"],
  ["MMC", "Marsh & McLennan", "NYSE"],
  ["VRTX", "Vertex Pharmaceuticals", "NASDAQ"],
  ["LRCX", "Lam Research", "NASDAQ"],
  ["PANW", "Palo Alto Networks", "NASDAQ"],
  ["REGN", "Regeneron Pharmaceuticals", "NASDAQ"],
  ["KLAC", "KLA Corporation", "NASDAQ"],
  ["SNPS", "Synopsys Inc.", "NASDAQ"],
  ["CDNS", "Cadence Design Systems", "NASDAQ"],
  ["MU", "Micron Technology", "NASDAQ"],
  ["PYPL", "PayPal Holdings", "NASDAQ"],
  ["COIN", "Coinbase Global", "NASDAQ"],
  ["SQ", "Block Inc.", "NYSE"],
  ["SHOP", "Shopify Inc.", "NYSE"],
  ["NKE", "Nike Inc.", "NYSE"],
  ["ROKU", "Roku Inc.", "NASDAQ"],
  ["PLTR", "Palantir Technologies", "NYSE"],
  ["SNOW", "Snowflake Inc.", "NYSE"],
  ["CRWD", "CrowdStrike Holdings", "NASDAQ"],
  ["ZS", "Zscaler Inc.", "NASDAQ"],
  ["DDOG", "Datadog Inc.", "NASDAQ"],
  ["NET", "Cloudflare Inc.", "NYSE"],
  ["MRVL", "Marvell Technology", "NASDAQ"],
  ["FTNT", "Fortinet Inc.", "NASDAQ"],
  ["ABNB", "Airbnb Inc.", "NASDAQ"],
  ["DASH", "DoorDash Inc.", "NASDAQ"],
  ["RIVN", "Rivian Automotive", "NASDAQ"],
  ["LCID", "Lucid Group", "NASDAQ"],
  ["F", "Ford Motor Company", "NYSE"],
  ["GM", "General Motors", "NYSE"],
  ["SOFI", "SoFi Technologies", "NASDAQ"],
  ["HOOD", "Robinhood Markets", "NASDAQ"],
  ["MSTR", "MicroStrategy Incorporated", "NASDAQ"],
  ["SMCI", "Super Micro Computer", "NASDAQ"],
  ["ARM", "Arm Holdings plc", "NASDAQ"],
  ["BABA", "Alibaba Group", "NYSE"],
  ["JD", "JD.com Inc.", "NASDAQ"],
  ["PDD", "PDD Holdings", "NASDAQ"],
  ["NIO", "NIO Inc.", "NYSE"],
  ["XPEV", "XPeng Inc.", "NYSE"],
  ["LI", "Li Auto Inc.", "NASDAQ"],
  ["TSM", "Taiwan Semiconductor", "NYSE"],
  ["ASML", "ASML Holding", "NASDAQ"],
  ["SAP", "SAP SE", "NYSE"],
  ["SONY", "Sony Group Corporation", "NYSE"],
  ["TM", "Toyota Motor Corporation", "NYSE"],
  ["HMC", "Honda Motor Co.", "NYSE"],
  ["BP", "BP plc", "NYSE"],
  ["SHEL", "Shell plc", "NYSE"],
  ["TTE", "TotalEnergies SE", "NYSE"],
  ["RIO", "Rio Tinto plc", "NYSE"],
  ["BHP", "BHP Group Limited", "NYSE"],
  ["VALE", "Vale S.A.", "NYSE"],
  ["FCX", "Freeport-McMoRan", "NYSE"],
  ["NEM", "Newmont Corporation", "NYSE"],
  ["GOLD", "Barrick Gold Corporation", "NYSE"],
  ["WFC", "Wells Fargo & Company", "NYSE"],
  ["USB", "U.S. Bancorp", "NYSE"],
  ["PNC", "PNC Financial Services", "NYSE"],
  ["SCHW", "Charles Schwab Corporation", "NYSE"],
  ["COF", "Capital One Financial", "NYSE"],
  ["MET", "MetLife Inc.", "NYSE"],
  ["AIG", "American International Group", "NYSE"],
  ["ALL", "Allstate Corporation", "NYSE"],
  ["TRV", "Travelers Companies", "NYSE"],
  ["CB", "Chubb Limited", "NYSE"],
  ["MO", "Altria Group", "NYSE"],
  ["MDT", "Medtronic plc", "NYSE"],
  ["BMY", "Bristol-Myers Squibb", "NYSE"],
  ["CI", "Cigna Group", "NYSE"],
  ["ELV", "Elevance Health", "NYSE"],
  ["HUM", "Humana Inc.", "NYSE"],
  ["CVS", "CVS Health Corporation", "NYSE"],
  ["WBA", "Walgreens Boots Alliance", "NASDAQ"],
  ["KR", "Kroger Co.", "NYSE"],
  ["TGT", "Target Corporation", "NYSE"],
  ["DG", "Dollar General", "NYSE"],
  ["DLTR", "Dollar Tree Inc.", "NASDAQ"],
  ["ROST", "Ross Stores Inc.", "NASDAQ"],
  ["YUM", "Yum! Brands Inc.", "NYSE"],
  ["CMG", "Chipotle Mexican Grill", "NYSE"],
  ["MAR", "Marriott International", "NASDAQ"],
  ["HLT", "Hilton Worldwide", "NYSE"],
  ["LVS", "Las Vegas Sands", "NYSE"],
  ["WYNN", "Wynn Resorts", "NASDAQ"],
  ["MGM", "MGM Resorts International", "NYSE"],
  ["DAL", "Delta Air Lines", "NYSE"],
  ["UAL", "United Airlines Holdings", "NASDAQ"],
  ["AAL", "American Airlines Group", "NASDAQ"],
  ["LUV", "Southwest Airlines", "NYSE"],
  ["UPS", "United Parcel Service", "NYSE"],
  ["FDX", "FedEx Corporation", "NYSE"],
  ["UNP", "Union Pacific Corporation", "NYSE"],
  ["CSX", "CSX Corporation", "NASDAQ"],
  ["NSC", "Norfolk Southern", "NYSE"],
  ["WM", "Waste Management Inc.", "NYSE"],
  ["RSG", "Republic Services", "NYSE"],
  ["EOG", "EOG Resources", "NYSE"],
  ["OXY", "Occidental Petroleum", "NYSE"],
  ["SLB", "Schlumberger Limited", "NYSE"],
  ["HAL", "Halliburton Company", "NYSE"],
  ["KMI", "Kinder Morgan", "NYSE"],
  ["PSX", "Phillips 66", "NYSE"],
  ["VLO", "Valero Energy", "NYSE"],
  ["MPC", "Marathon Petroleum", "NYSE"],
  ["DUK", "Duke Energy Corporation", "NYSE"],
  ["SO", "Southern Company", "NYSE"],
  ["NEE", "NextEra Energy", "NYSE"],
  ["D", "Dominion Energy", "NYSE"],
  ["AEP", "American Electric Power", "NASDAQ"],
  ["EXC", "Exelon Corporation", "NASDAQ"],
  ["EQIX", "Equinix Inc.", "NASDAQ"],
  ["PLD", "Prologis Inc.", "NYSE"],
  ["AMT", "American Tower Corporation", "NYSE"],
  ["CCI", "Crown Castle Inc.", "NYSE"],
  ["SPG", "Simon Property Group", "NYSE"],
  ["O", "Realty Income Corporation", "NYSE"],
  ["VICI", "VICI Properties Inc.", "NYSE"],
  ["EA", "Electronic Arts Inc.", "NASDAQ"],
  ["TTWO", "Take-Two Interactive", "NASDAQ"],
  ["RBLX", "Roblox Corporation", "NYSE"],
  ["U", "Unity Software Inc.", "NYSE"],
  ["DKNG", "DraftKings Inc.", "NASDAQ"],
  ["PINS", "Pinterest Inc.", "NYSE"],
  ["SNAP", "Snap Inc.", "NYSE"],
  ["TWLO", "Twilio Inc.", "NYSE"],
  ["ZM", "Zoom Video Communications", "NASDAQ"],
  ["DOCU", "DocuSign Inc.", "NASDAQ"],
  ["OKTA", "Okta Inc.", "NASDAQ"],
  ["TEAM", "Atlassian Corporation", "NASDAQ"],
  ["WDAY", "Workday Inc.", "NASDAQ"],
  ["ADSK", "Autodesk Inc.", "NASDAQ"],
  ["ANET", "Arista Networks", "NYSE"],
  ["ON", "ON Semiconductor", "NASDAQ"],
  ["NXPI", "NXP Semiconductors", "NASDAQ"],
  ["STX", "Seagate Technology", "NASDAQ"],
  ["WDC", "Western Digital", "NASDAQ"],
  ["HPQ", "HP Inc.", "NYSE"],
  ["DELL", "Dell Technologies", "NYSE"],
  ["HPE", "Hewlett Packard Enterprise", "NYSE"],
  ["CARR", "Carrier Global Corporation", "NYSE"],
  ["OTIS", "Otis Worldwide Corporation", "NYSE"],
  ["EMR", "Emerson Electric", "NYSE"],
  ["ETN", "Eaton Corporation", "NYSE"],
  ["ITW", "Illinois Tool Works", "NYSE"],
  ["PH", "Parker-Hannifin Corporation", "NYSE"],
  ["ROK", "Rockwell Automation", "NYSE"],
  ["SPY", "SPDR S&P 500 ETF", "NYSE"],
  ["QQQ", "Invesco QQQ Trust", "NASDAQ"],
  ["IWM", "iShares Russell 2000 ETF", "NYSE"],
  ["DIA", "SPDR Dow Jones Industrial Average ETF", "NYSE"],
  ["VTI", "Vanguard Total Stock Market ETF", "NYSE"],
  ["VOO", "Vanguard S&P 500 ETF", "NYSE"],
  ["ARKK", "ARK Innovation ETF", "NYSE"],
  ["XLF", "Financial Select Sector SPDR", "NYSE"],
  ["XLK", "Technology Select Sector SPDR", "NYSE"],
  ["XLE", "Energy Select Sector SPDR", "NYSE"],
  ["XLV", "Health Care Select Sector SPDR", "NYSE"],
];

export const STOCK_INSTRUMENTS: CatalogInstrument[] = STOCK_ROWS.map(([ticker, name, exchange]) => {
  const baseId = ticker.toLowerCase().replace(/\./g, "");
  const id = ticker === "DASH" ? "dashstock" : ticker === "STX" ? "stxstock" : baseId;
  return stk(id, ticker, name, exchange);
});

export const COMMODITY_INSTRUMENTS: CatalogInstrument[] = [
  cmd("xauusd", "XAU/USD", "Gold Spot", "TVC:GOLD", "GC=F"),
  cmd("silver", "XAG/USD", "Silver Spot", "TVC:SILVER", "SI=F"),
  cmd("platinum", "XPT/USD", "Platinum", "TVC:PLATINUM", "PL=F"),
  cmd("palladium", "XPD/USD", "Palladium", "TVC:PALLADIUM", "PA=F"),
  cmd("wti", "WTI/USD", "Crude Oil WTI", "NYMEX:CL1!", "CL=F"),
  cmd("brent", "BRT/USD", "Brent Crude", "TVC:UKOIL", "BZ=F"),
  cmd("natgas", "NGS/USD", "Natural Gas", "NYMEX:NG1!", "NG=F"),
  cmd("gasoline", "RBOB/USD", "Gasoline RBOB", "NYMEX:RB1!", "RB=F"),
  cmd("heating", "HO/USD", "Heating Oil", "NYMEX:HO1!", "HO=F"),
  cmd("copper", "HG/USD", "Copper", "COMEX:HG1!", "HG=F"),
  cmd("aluminum", "ALI/USD", "Aluminum", "TVC:ALUMINUM", "ALI=F"),
  cmd("wheat", "WHT/USD", "Wheat", "CBOT:ZW1!", "ZW=F"),
  cmd("corn", "CRN/USD", "Corn", "CBOT:ZC1!", "ZC=F"),
  cmd("soybeans", "SOY/USD", "Soybeans", "CBOT:ZS1!", "ZS=F"),
  cmd("coffee", "KC/USD", "Coffee", "ICEUS:KC1!", "KC=F"),
  cmd("sugar", "SB/USD", "Sugar", "ICEUS:SB1!", "SB=F"),
  cmd("cotton", "CT/USD", "Cotton", "ICEUS:CT1!", "CT=F"),
  cmd("cocoa", "CC/USD", "Cocoa", "ICEUS:CC1!", "CC=F"),
  cmd("lumber", "LBR/USD", "Lumber", "CME:LBS1!", "LBS=F"),
];

export const INDEX_INSTRUMENTS: CatalogInstrument[] = [
  idx("spx", "SPX/USD", "S&P 500", "SP:SPX", "^GSPC"),
  idx("ndx", "NDQ/USD", "Nasdaq 100", "NASDAQ:NDX", "^NDX"),
  idx("dji", "DOW/USD", "Dow Jones Industrial", "DJ:DJI", "^DJI"),
  idx("rut", "RUT/USD", "Russell 2000", "TVC:RUT", "^RUT"),
  idx("vix", "VIX/USD", "CBOE Volatility Index", "TVC:VIX", "^VIX"),
  idx("ftse", "FTS/GBP", "FTSE 100", "TVC:UKX", "^FTSE"),
  idx("dax", "DAX/EUR", "DAX 40", "XETR:DAX", "^GDAXI"),
  idx("cac", "CAC/EUR", "CAC 40", "TVC:CAC40", "^FCHI"),
  idx("eustx", "STX/EUR", "EURO STOXX 50", "TVC:SX5E", "^STOXX50E"),
  idx("ibex", "IBX/EUR", "IBEX 35", "TVC:IBEX35", "^IBEX"),
  idx("smi", "SMI/CHF", "Swiss Market Index", "TVC:SMI", "^SSMI"),
  idx("aex", "AEX/EUR", "AEX Netherlands", "TVC:AEX", "^AEX"),
  idx("nikkei", "NKI/USD", "Nikkei 225", "TVC:NI225", "^N225"),
  idx("topix", "TPX/JPY", "TOPIX", "TVC:TOPIX", "^TOPX"),
  idx("hsi", "HSI/HKD", "Hang Seng", "TVC:HSI", "^HSI"),
  idx("csi300", "CSI/CNY", "CSI 300", "TVC:CSI300", "000300.SS"),
  idx("asx", "ASX/AUD", "ASX 200", "TVC:AS51", "^AXJO"),
  idx("nifty", "NIF/INR", "Nifty 50", "NSE:NIFTY", "^NSEI"),
  idx("sensex", "SEN/INR", "BSE Sensex", "BSE:SENSEX", "^BSESN"),
  idx("tsx", "TSX/CAD", "S&P/TSX Composite", "TVC:TSX", "^GSPTSE"),
  idx("bovespa", "BVSP/BRL", "Bovespa", "TVC:IBOV", "^BVSP"),
  idx("kospi", "KOS/KRW", "KOSPI", "TVC:KOSPI", "^KS11"),
  idx("twse", "TAI/TWD", "Taiwan Weighted", "TVC:TWII", "^TWII"),
];

const CRYPTO_USDT_BASES: Array<[string, string]> = [
  ["BTC", "Bitcoin"],
  ["ETH", "Ethereum"],
  ["BNB", "BNB"],
  ["SOL", "Solana"],
  ["XRP", "Ripple"],
  ["ADA", "Cardano"],
  ["DOGE", "Dogecoin"],
  ["AVAX", "Avalanche"],
  ["DOT", "Polkadot"],
  ["LINK", "Chainlink"],
  ["MATIC", "Polygon"],
  ["POL", "Polygon Ecosystem"],
  ["LTC", "Litecoin"],
  ["BCH", "Bitcoin Cash"],
  ["UNI", "Uniswap"],
  ["ATOM", "Cosmos"],
  ["XLM", "Stellar"],
  ["FIL", "Filecoin"],
  ["NEAR", "NEAR Protocol"],
  ["APT", "Aptos"],
  ["ARB", "Arbitrum"],
  ["OP", "Optimism"],
  ["INJ", "Injective"],
  ["SUI", "Sui"],
  ["SEI", "Sei"],
  ["TIA", "Celestia"],
  ["RENDER", "Render"],
  ["FET", "Fetch.ai"],
  ["GRT", "The Graph"],
  ["AAVE", "Aave"],
  ["MKR", "Maker"],
  ["CRV", "Curve DAO"],
  ["SAND", "The Sandbox"],
  ["MANA", "Decentraland"],
  ["AXS", "Axie Infinity"],
  ["GALA", "Gala"],
  ["ENJ", "Enjin Coin"],
  ["IMX", "Immutable"],
  ["RUNE", "THORChain"],
  ["ALGO", "Algorand"],
  ["VET", "VeChain"],
  ["HBAR", "Hedera"],
  ["ICP", "Internet Computer"],
  ["EGLD", "MultiversX"],
  ["FLOW", "Flow"],
  ["XTZ", "Tezos"],
  ["EOS", "EOS"],
  ["KAVA", "Kava"],
  ["ROSE", "Oasis Network"],
  ["ZEC", "Zcash"],
  ["DASH", "Dash"],
  ["ETC", "Ethereum Classic"],
  ["THETA", "Theta Network"],
  ["KSM", "Kusama"],
  ["1INCH", "1inch Network"],
  ["COMP", "Compound"],
  ["SNX", "Synthetix"],
  ["YFI", "yearn.finance"],
  ["BAL", "Balancer"],
  ["LDO", "Lido DAO"],
  ["RPL", "Rocket Pool"],
  ["PENDLE", "Pendle"],
  ["JUP", "Jupiter"],
  ["WIF", "dogwifhat"],
  ["PEPE", "Pepe"],
  ["SHIB", "Shiba Inu"],
  ["FLOKI", "FLOKI"],
  ["BONK", "Bonk"],
  ["ORDI", "ORDI"],
  ["STX", "Stacks"],
  ["CFX", "Conflux"],
  ["AR", "Arweave"],
  ["WLD", "Worldcoin"],
  ["PYTH", "Pyth Network"],
  ["JTO", "Jito"],
  ["STRK", "Starknet"],
  ["ZK", "zkSync"],
  ["ENA", "Ethena"],
  ["ONDO", "Ondo Finance"],
  ["TAO", "Bittensor"],
  ["TRX", "TRON"],
  ["XMR", "Monero"],
  ["TON", "Toncoin"],
  ["NOT", "Notcoin"],
  ["S", "Sonic"],
  ["CAKE", "PancakeSwap"],
  ["DYDX", "dYdX"],
  ["GMX", "GMX"],
  ["BLUR", "Blur"],
  ["APE", "ApeCoin"],
  ["CHZ", "Chiliz"],
  ["SFP", "SafePal"],
  ["QNT", "Quant"],
  ["ZIL", "Zilliqa"],
  ["IOTA", "IOTA"],
  ["NEO", "NEO"],
  ["WAVES", "Waves"],
  ["KNC", "Kyber Network"],
  ["BAT", "Basic Attention Token"],
  ["ZRX", "0x Protocol"],
  ["ANKR", "Ankr"],
  ["CELO", "Celo"],
  ["MINA", "Mina Protocol"],
  ["SC", "Siacoin"],
  ["HOT", "Holo"],
  ["RVN", "Ravencoin"],
  ["DGB", "DigiByte"],
  ["ICX", "ICON"],
  ["ONT", "Ontology"],
  ["QTUM", "Qtum"],
  ["IOST", "IOST"],
  ["ZEN", "Horizen"],
  ["SKL", "SKALE"],
  ["COTI", "COTI"],
  ["CHR", "Chromia"],
  ["SXP", "Solar"],
  ["BAND", "Band Protocol"],
  ["RLC", "iExec RLC"],
  ["STORJ", "Storj"],
  ["OCEAN", "Ocean Protocol"],
  ["MASK", "Mask Network"],
  ["LPT", "Livepeer"],
  ["AUDIO", "Audius"],
  ["API3", "API3"],
  ["UMA", "UMA"],
  ["BNT", "Bancor"],
  ["LQTY", "Liquity"],
  ["SSV", "SSV Network"],
  ["MAGIC", "Treasure"],
  ["RDNT", "Radiant Capital"],
  ["ID", "SPACE ID"],
  ["ACE", "Fusionist"],
  ["NTRN", "Neutron"],
  ["TWT", "Trust Wallet Token"],
  ["BEAM", "Beam"],
  ["PIXEL", "Pixels"],
  ["PORTAL", "Portal"],
  ["AEVO", "Aevo"],
  ["ETHFI", "ether.fi"],
  ["SAGA", "Saga"],
  ["REZ", "Renzo"],
  ["BB", "BounceBit"],
  ["LISTA", "Lista DAO"],
  ["ZRO", "LayerZero"],
  ["IO", "IO.NET"],
];

export const CRYPTO_USDT_INSTRUMENTS: CatalogInstrument[] = CRYPTO_USDT_BASES.map(([base, name]) => {
  const id = base === "DASH" ? "dashcoin" : base === "STX" ? "stacks" : base.toLowerCase();
  return cr(id, base, name);
});

const CRYPTO_EUR_BASES: Array<[string, string]> = [
  ["BTC", "Bitcoin EUR"],
  ["ETH", "Ethereum EUR"],
  ["BNB", "BNB EUR"],
  ["SOL", "Solana EUR"],
  ["XRP", "Ripple EUR"],
  ["ADA", "Cardano EUR"],
  ["DOGE", "Dogecoin EUR"],
  ["AVAX", "Avalanche EUR"],
  ["DOT", "Polkadot EUR"],
  ["LINK", "Chainlink EUR"],
  ["LTC", "Litecoin EUR"],
  ["BCH", "Bitcoin Cash EUR"],
  ["UNI", "Uniswap EUR"],
  ["ATOM", "Cosmos EUR"],
  ["XLM", "Stellar EUR"],
  ["NEAR", "NEAR EUR"],
  ["APT", "Aptos EUR"],
  ["ARB", "Arbitrum EUR"],
  ["OP", "Optimism EUR"],
  ["INJ", "Injective EUR"],
  ["SUI", "Sui EUR"],
  ["SEI", "Sei EUR"],
  ["TIA", "Celestia EUR"],
  ["FET", "Fetch.ai EUR"],
  ["GRT", "The Graph EUR"],
  ["AAVE", "Aave EUR"],
  ["MKR", "Maker EUR"],
  ["SAND", "The Sandbox EUR"],
  ["MANA", "Decentraland EUR"],
  ["PEPE", "Pepe EUR"],
  ["SHIB", "Shiba Inu EUR"],
  ["TRX", "TRON EUR"],
  ["ETC", "Ethereum Classic EUR"],
  ["FIL", "Filecoin EUR"],
  ["ALGO", "Algorand EUR"],
  ["VET", "VeChain EUR"],
  ["HBAR", "Hedera EUR"],
  ["ICP", "Internet Computer EUR"],
  ["EGLD", "MultiversX EUR"],
  ["WLD", "Worldcoin EUR"],
  ["ENA", "Ethena EUR"],
  ["ONDO", "Ondo Finance EUR"],
  ["RENDER", "Render EUR"],
  ["JUP", "Jupiter EUR"],
  ["WIF", "dogwifhat EUR"],
  ["BONK", "Bonk EUR"],
  ["STX", "Stacks EUR"],
  ["PYTH", "Pyth Network EUR"],
  ["STRK", "Starknet EUR"],
  ["ZK", "zkSync EUR"],
  ["TON", "Toncoin EUR"],
  ["CAKE", "PancakeSwap EUR"],
  ["CHZ", "Chiliz EUR"],
  ["QNT", "Quant EUR"],
];

export const CRYPTO_EUR_INSTRUMENTS: CatalogInstrument[] = CRYPTO_EUR_BASES.map(([base, name]) =>
  cre(`${base.toLowerCase()}eur`, base, name),
);
