import { useEffect, useState } from "react";
import { TrendingUp, BarChart3, LineChart, Shield, ArrowUpRight, ArrowDownRight, Activity } from "lucide-react";

export function TradingHomePage() {
  return (
    <div className="min-h-screen bg-[#0a0a0f] text-white">
      {/* Navigation */}
      <nav className="border-b border-white/10 px-6 py-4">
        <div className="mx-auto flex max-w-7xl items-center justify-between">
          <div className="flex items-center gap-3">
            <Activity className="h-6 w-6 text-emerald-400" />
            <span className="text-lg font-bold">TradeToros</span>
          </div>
          <div className="flex items-center gap-6 text-sm text-zinc-400">
            <a href="/dashboard" className="hover:text-white transition">Dashboard</a>
            <a href="/trading" className="hover:text-white transition">Trading</a>
            <a href="/signals" className="hover:text-white transition">Signals</a>
            <a href="/portfolio" className="hover:text-white transition">Portfolio</a>
            <a href="/admin" className="hover:text-white transition">Admin</a>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="mx-auto max-w-7xl px-6 py-20">
        <div className="text-center">
          <h1 className="text-5xl font-bold tracking-tight">
            AI-Powered
            <span className="bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-transparent"> Trading Intelligence</span>
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg text-zinc-400">
            Real-time market analysis, AI-driven signals, and portfolio management
            powered by multi-model artificial intelligence.
          </p>
          <div className="mt-10 flex items-center justify-center gap-4">
            <a
              href="/dashboard"
              className="rounded-xl bg-emerald-500 px-8 py-3.5 text-sm font-semibold text-black transition hover:bg-emerald-400"
            >
              Launch Dashboard
            </a>
            <a
              href="/signals"
              className="rounded-xl border border-white/20 px-8 py-3.5 text-sm font-semibold text-white transition hover:bg-white/10"
            >
              View Signals
            </a>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="mx-auto max-w-7xl px-6 py-20">
        <div className="grid gap-6 md:grid-cols-3">
          <FeatureCard
            icon={<TrendingUp className="h-6 w-6 text-emerald-400" />}
            title="4D Market Analysis"
            description="Trend, Flow, Correlation, and Risk/Reward analysis across crypto and stock markets."
          />
          <FeatureCard
            icon={<BarChart3 className="h-6 w-6 text-cyan-400" />}
            title="AI Signal Engine"
            description="Real-time trading signals generated by multi-model AI (Gemini, Groq, xAI)."
          />
          <FeatureCard
            icon={<Shield className="h-6 w-6 text-emerald-400" />}
            title="Portfolio Protection"
            description="Risk management with intelligent stop-losses and position sizing recommendations."
          />
        </div>
      </section>

      {/* Market Ticker */}
      <section className="border-t border-white/10 px-6 py-12">
        <div className="mx-auto max-w-7xl">
          <h2 className="mb-6 text-lg font-semibold text-zinc-300">Live Market Overview</h2>
          <div className="grid gap-4 md:grid-cols-4">
            <TickerCard symbol="BTC/USD" price="67,234" change={2.34} />
            <TickerCard symbol="ETH/USD" price="3,456" change={-1.23} />
            <TickerCard symbol="SOL/USD" price="142.50" change={5.67} />
            <TickerCard symbol="SPX" price="5,234" change={0.45} />
          </div>
        </div>
      </section>
    </div>
  );
}

function FeatureCard({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-8">
      <div className="mb-4 rounded-xl bg-white/5 p-3 w-fit">{icon}</div>
      <h3 className="mb-3 text-lg font-semibold">{title}</h3>
      <p className="text-sm leading-relaxed text-zinc-400">{description}</p>
    </div>
  );
}

function TickerCard({ symbol, price, change }: { symbol: string; price: string; change: number }) {
  const isUp = change > 0;
  return (
    <div className="rounded-xl border border-white/10 bg-white/[0.02] p-4">
      <div className="mb-2 text-sm text-zinc-500">{symbol}</div>
      <div className="flex items-center justify-between">
        <span className="text-xl font-bold">${price}</span>
        <span className={`flex items-center gap-1 text-sm font-medium ${isUp ? 'text-emerald-400' : 'text-red-400'}`}>
          {isUp ? <ArrowUpRight className="h-4 w-4" /> : <ArrowDownRight className="h-4 w-4" />}
          {Math.abs(change)}%
        </span>
      </div>
    </div>
  );
}
